import type { Panel } from "./types"

// TODO: replace with real data

export const panels: Panel[] = [
    {
        id: 0,
        label: "Lorem Ipsum 01",
        panelColor: "#00B9BD",
        textColor: "#004853",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel0/800/600",
    },
    {
        id: 1,
        label: "Lorem Ipsum 02",
        panelColor: "#4D17B7",
        textColor: "#FFFFFF",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel1/800/600",
    },
    {
        id: 2,
        label: "Lorem Ipsum 03",
        panelColor: "#FFA629",
        textColor: "#0C0C0C",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel2/800/600",
    },
    {
        id: 3,
        label: "Lorem Ipsum 04",
        panelColor: "#F2D6B1",
        textColor: "#0C0C0C",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel3/800/600",
    },
    {
        id: 4,
        label: "Lorem Ipsum 05",
        panelColor: "#C12400",
        textColor: "#FFE6E0",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel4/800/600",
    },
    {
        id: 5,
        label: "Lorem Ipsum 06",
        panelColor: "#004853",
        textColor: "#7DF0F2",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel5/800/600",
    },
    {
        id: 6,
        label: "Lorem Ipsum 07",
        panelColor: "#00BCD4",
        textColor: "#000000",
        title: "Objetivos",
        description: "É a área responsável por incorporar experiências e boas práticas de mercado, adaptando-as ao contexto marxista-leninista do nosso coletivo. Isso garante não apenas uma estrutura organizacional bem definida, alinhada aos princípios do centralismo democrático, mas também modelos de trabalho eficientes para a entrega de soluções digitais.",
        activitiesTitle: "Atividades Principais",
        activities: ["Treinamentos sobre metodologia ágeis para otimizar a entrega de projetos;", "Atuar diretamente nos times de desenvolvimento das soluções planejadas."],
        image: "https://picsum.photos/seed/panel6/800/600",
    },
]
