import type { Metadata } from 'next';
import './globals.css';

import PrelineScriptWrapper from '@components/common/PrelineScriptWrapper';
import { barlowCondensed } from './fonts';
import { SvgDefs } from './ui/SvgDefs';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${barlowCondensed.className} antialiased`}>
                <SvgDefs />
                {children}
                <PrelineScriptWrapper />
            </body>
        </html>
    );
}
